version: '2'
services:
    syscomarch-app:
        image: syscomarch
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://syscomarch-postgresql:5432/SysComArch
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    syscomarch-postgresql:
        extends:
            file: postgresql.yml
            service: syscomarch-postgresql
